### ISSUE TITLE
Retrieving one record from a 1.2 GB file takes too long

### ISSUE THREAD

**Issue by hgardneriv** [miknevinas/log_project#2]
We generally test with large files and expect an optimized response time. In this case, I copied over a large file to hadoop.log to get a sense of how the app performs with large files. In this test it is taking around 15 seconds to get the last line of the file:

`$ time curl "http://localhost:3000/logs/hadoop/1" 
{"total":1,"lines":["2023-01-04 08:35:49-06 Harrys-MBP-2 SoftwareUpdateNotificationManager[677]: AssertionMgr: Could not cancel com.apple.softwareupdate.NotifyAgentAssertion-BadgingCountChanged assertion - no assertion found for pid 677"]}curl "http://localhost:3000/logs/hadoop/1"  0.00s user 0.01s system 0% cpu 15.026 total`

This is because the entire file is being processed front to back reading each line. There is an optimized way to approach this which involves seeking to the end of the file, as a first step. Happy to elaborate more on this over email. BTW - Using streams is the 100% the right approach but the mechanism to read data could be improved.

**Comment by miknevinas** [comment]
I've refactored the code using using unix commands to expedite the process. According to my stopwatch, I was able to almost double the speed in which data was returned, though your results may vary.

I understand this solution discards streams - I was unable to come up with a satisfactory solution utilizing streams without spending a lengthy amount of time hacking something horrific or using an external library.
